apiVersion: v1 
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPorts: 80
  - name: almalinux
    image: almalinux:8
    command: ["sleep", "30"]