apiVersion: v1 
kind: pod 
metadata:
  name: label-demo
  labels:
    course: devops
    triner: "nagaraju thoti"
spec:
  containers:
    - name: hello-pod
      image: nginx
      ports:
      - containerPort: 80
