apiVersion: v1 
kind: pod 
metadata:
  name: annotations
  labels: 
    course: DevOps
    Trainer: Nagaraju
  annotations:
    com.roboshop.trining.duration: "120 hours"
    jenkins url : "https://jenkins.com/roboshop/catalogue#45"
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80
